### ISSUE TITLE
redefinición de #=

### ISSUE THREAD

**Issue by maximoprieto** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#12]
Al salvar el método:
![image](https://user-images.githubusercontent.com/7443682/29977997-c69f157e-8f15-11e7-86c7-f1d276ff49d8.png)

**Comment by maximoprieto** [comment]
Después de eso, el browser comienza a dar MNUs varios al hacer click en categorías de mensajes e incluso desaparece el DObject sobre el que estaba programando. Tengo cerrar Cuis y arrancar de nuevo.

**Comment by hernanwilkinson** [comment]
Fijate que definicion de = que hiciste no devuelve un booleano, te olvidaste el ^
Lo que sucede es que esta redefiniendo el = de la clase por lo que las herramientas se mambean al no devolver un booleano ...

**Comment by maximoprieto** [comment]
Shit! Error de principiante.

Gracias


2017-09-01 16:16 GMT-03:00 Hernan Wilkinson <notifications@github.com>:
