### ISSUE TITLE
"collaborators" y mensaje cuando no hay ninguno

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#17]
* debería decir "collaborators" en lugar de colaborators
* el mensaje cuando no hay ninguno dice "instance variables"

![screenshot_20170907_071456](https://user-images.githubusercontent.com/519947/30158695-72072944-939c-11e7-8201-3299eecb3cbd.png)

**Comment by hernanwilkinson** [comment]
Listo, arreglado, estara en la proxima version.
Renombre todos los mensajes y classes que usaban Colaborator

**Comment by maximoprieto** [comment]
👌

2017-09-07 15:54 GMT-03:00 Hernan Wilkinson <notifications@github.com>:

**Comment by ngarbezza** [comment]
Verificado!
