### ISSUE TITLE
Agregar shortcut (cmd-t) para run tests en panel de categorías de mensajes

### ISSUE THREAD

**Issue by maximoprieto** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#18]
Ahora no está:
![image](https://user-images.githubusercontent.com/7443682/30183161-cc896262-93ef-11e7-91c1-9e6ce32c76e3.png)

**Comment by hernanwilkinson** [comment]
El menu de categoria de mensajes no soporta shurtcuts en Cuis... habria que ampliar Cuis para eso...

**Comment by ngarbezza** [comment]
ahora ya lo tiene... confirmado que funciona en versión 3426
