### ISSUE TITLE
Agregar shorcut para inspect (cmd-i) en el panel de DObjects

### ISSUE THREAD

**Issue by maximoprieto** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#19]
![image](https://user-images.githubusercontent.com/7443682/30183288-3d71bb96-93f0-11e7-8ad6-8a6366bd18a0.png)

**Comment by hernanwilkinson** [comment]
Hecho.

**Comment by ngarbezza** [comment]
Verificado! No puedo cerrar el issue, @maximoprieto vos podés?
