### ISSUE TITLE
Creating denotative objects named as "known" classes crashes the image

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#2]
If you try to create a denotative object called `True` the image crashes (it enters into the emergency evaluator):

```smalltalk
ObjectBuilder create: #True
	collaboratorNames: ''
	in: 'DenotativeObject-TestSupport'
```

Results in: 

![screenshot_20170802_092548](https://user-images.githubusercontent.com/519947/29003508-97676126-7a8e-11e7-885d-06b8bd3e711a.png)

**Comment by hernanwilkinson** [comment]
Fixed on commit https://github.com/hernanwilkinson/Cuis-Smalltalk-DenotativeObject/commit/35c496918ed91316b56d52d7cfe71a1031c82e53.
Please verify it and close the issue if work as expected
