### ISSUE TITLE
Debería ser posible agregar nuevas categorías de clases desde el menu contextual

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#21]
Actualmente sólo se pueden crear nuevas al crear un objeto nuevo

**Comment by hernanwilkinson** [comment]
Como las categorias aparecen automaticamente es que no habilitamos esta opcion... no se puede tener que aparezcan automaticamente y agregarlas a mano. De la misma manera las categorias desaparecen automaticamente. Esto lo hicimos asi para que sea mas facil para los alumnos usarlo
