### ISSUE TITLE
Menu contextual de DOs se puede acceder sin tener seleccionada ninguna categoría

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#22]
![screenshot_20180326_203826](https://user-images.githubusercontent.com/519947/37938797-fa71c604-3135-11e8-91a6-4a510e5bf555.png)

Algunas opciones simplemente no hacen nada pero el `add object...` rompe

**Comment by hernanwilkinson** [comment]
Arreglado

**Comment by ngarbezza** [comment]
Verificado en v3289!
