### ISSUE TITLE
Rename DO deja poner espacios en el nombre

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#23]
Lo loco es que no rompe, pero creo que no queremos eso :)

![screenshot_20180329_210609](https://user-images.githubusercontent.com/519947/38119002-1251be12-3395-11e8-86e5-34e98762c506.png)

**Comment by hernanwilkinson** [comment]
muy loco! ahi lo arregle

**Comment by ngarbezza** [comment]
Confimado! Funciona en v3289
