### ISSUE TITLE
Agregar rename de Paquetes

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#24]
![screenshot_20180405_052445](https://user-images.githubusercontent.com/519947/38354938-be460fce-3891-11e8-875e-a45d2da1cd04.png)

**Comment by hernanwilkinson** [comment]
Agregado en la ultima version (1.29)
Requiere el Change set 3289-CuisCore-HernanWilkinson-2018Apr05-13h39m-HAW.1.cs loaded que ya fue mandado para ser incluido en Cuis.

**Comment by ngarbezza** [comment]
Confirmado que funciona en dicha versión!
