### ISSUE TITLE
Creating DOs through "Unknown Variable" dialog does not refresh DOs list

### ISSUE THREAD

**Issue by ngarbezza** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#3]
Steps to reproduce:

1. Reference an unexisting DenotativeObject from a method
2. Save the method and choose "define new denotative object"
3. The object is created but not shown in the "second panel" with all the DOs
4. You need to go to another package and go back to see the new object

**Comment by hernanwilkinson** [comment]
Solved. When a DO is created that way the DO list is updated
