### ISSUE TITLE
Text cannot be accepted in this part of the browser

### ISSUE THREAD

**Issue by gstn-caruso** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#5]
When you open DenotativeBrowser a blank space is available to start writing where you should put the DenotativeObject definition.

If you define an object there, you just get the `Text cannot be accepted in this part of the browser` error.

![image](https://user-images.githubusercontent.com/12160875/29596367-2f49b5d2-8793-11e7-92b0-ab0ea909049f.png)

**Comment by hernanwilkinson** [comment]
Solved. Now when no category is selected the code pane is disabled
