### ISSUE TITLE
aviso de redefinición #initialize

### ISSUE THREAD

**Issue by maximoprieto** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#6]
![image](https://user-images.githubusercontent.com/7443682/29853325-ac9a8296-8d15-11e7-9260-8fc66505319f.png)

Habría que ver qué debería decir el aviso. Se podría poner el parent correspondiente (sin class) como techo, o DenotativeObject; podrían hacer de "proxies" de las clases reales (sólo para bancarse el aviso); se podría eliminar el aviso. No lo tengo claro.

**Comment by maximoprieto** [comment]
Me ocurrió cuando hice rename message porque lo había escrito mal

**Comment by hernanwilkinson** [comment]
Lo resolví de la siguiente manera:
- Cuando está redefiniendo un mensaje que este en DenotativeObject class o superclase muestra el siguiente mensaje (como el caso de #initialize):
<img width="943" alt="screen shot 2017-08-30 at 9 22 05 am" src="https://user-images.githubusercontent.com/58615/29872219-fe6b324c-8d64-11e7-966b-2293f311cc32.png">
- Cuando se está redefiniendo un mensaje de un parent, muestra el siguiente mensaje:
<img width="934" alt="screen shot 2017-08-30 at 9 22 45 am" src="https://user-images.githubusercontent.com/58615/29872234-1a8b949e-8d65-11e7-9a6a-2caf7fe77131.png">

Estará disponible en la próxima versión.

**Comment by maximoprieto** [comment]
Perfecto
