### ISSUE TITLE
Ejecuto test con DObject nuevo y asume nil

### ISSUE THREAD

**Issue by maximoprieto** [hernanwilkinson/Cuis-Smalltalk-DenotativeObject#8]
Comienzo con imagen virgen; hago fileIn del DObject ListTest para reimplementar List a partir de una suite de tests preexistentes; cuando ejecuto un test que referencia a List (que no está creado), en lugar de ofrecerme de crear un nuevo DO lo asume como nil, ergo: MNU:

![image](https://user-images.githubusercontent.com/7443682/29950254-e1813cf8-8e90-11e7-8e8e-c6bc2c9d8884.png)

**Comment by maximoprieto** [comment]
Si decido continuar implementando, vuela todo y se cierra Cuis. Si cierro el debugger, creo los DObjects referenciados y vuelvo a ejecutar el test, funciona bien.

**Comment by hernanwilkinson** [comment]
El problema es que hiciste un file in de un metodo que referencia a algo que no existe, en este caso List.
El file in en este caso inicializa esa referencia con nil, no detiene el proceso de file in porque sino nunca se podrian cargar referencias ciruclares que estan en archivos distintos...
Para este caso no queda otra que crear el objeto como lo terminaste hanciendo.
No se bien porque se te colgo cuando continuaste con el debugger, habria que ver que mensaje fue el que implementaste... yo lo hice aca y no pude reproducir esa parte

**Comment by maximoprieto** [comment]
Ok.
